spring:
#jdbc ??
  datasource:
    url: jdbc:oracle:thin:@192.168.123.180:1521:XE
    username: system
    password: 1234
    driver-class-name: oracle.jdbc.driver.OracleDriver

mybatis:
  mapper-locations: mapper/**/*.xml
  type-aliases-package: com.delivery.deliveryback